root: true

extends: "eslint:recommended"

env:
  browser: true
  es6: true
  node: true

globals:
  jasmine: true

rules:
  array-bracket-spacing: 0
  array-callback-return: 0
  arrow-body-style: 0
  arrow-parens: [2, "as-needed"]
  arrow-spacing: [2, {before: true, after: true}]
  accessor-pairs: 0
  block-scoped-var: 0
  block-spacing: 2
  brace-style: [2, "stroustrup", {allowSingleLine: true}]
  callback-return: 0
  camelcase: [2, {properties: "always"}]
  comma-dangle: 2
  comma-spacing: 2
  comma-style: [2, "last"]
  complexity: [0, 10]
  computed-property-spacing: [2, "never"]
  consistent-return: 0
  consistent-this: 0
  constructor-super: 2
  curly: [2, "multi-line"]
  default-case: 2
  dot-location: [2, "property"]
  dot-notation: [2, {allowKeywords: true}]
  eol-last: 2
  eqeqeq: 2
  func-names: 0
  func-style: [2, "declaration", {allowArrowFunctions: true }]
  generator-star-spacing: [2, {before: false, after: true}]
  guard-for-in: 2
  global-require: 0
  handle-callback-err: 0
  id-blacklist: 0
  id-length: 0
  id-match: 0
  indent: [2, 2, {SwitchCase: 1, VariableDeclarator: 2}]
  init-declarations: 0
  jsx-quotes: 1
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  keyword-spacing: 2
  linebreak-style: 0
  lines-around-comment: 0
  max-depth: 0
  max-len: 0
  max-nested-callbacks: 0
  max-params: 0
  max-statements: 0
  max-statements-per-line: 0
  new-cap: 2
  new-parens: 2
  newline-after-var: 0
  newline-before-return: 0
  newline-per-chained-call: 0
  no-alert: 2
  no-array-constructor: 2
  no-bitwise: 0
  no-caller: 2
  no-case-declarations: 2
  no-catch-shadow: 0
  no-class-assign: 2
  no-cond-assign: 2
  no-confusing-arrow: 0
  no-console: 2
  no-const-assign: 2
  no-constant-condition: 2
  no-continue: 0
  no-control-regex: 2
  no-debugger: 2
  no-delete-var: 2
  no-div-regex: 0
  no-dupe-args: 2
  no-dupe-class-members: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-duplicate-imports: 2
  no-else-return: 0
  no-empty: 2
  no-empty-character-class: 2
  no-empty-function: 0
  no-empty-pattern: 2
  no-eq-null: 0
  no-eval: 2
  no-ex-assign: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-boolean-cast: 2
  no-extra-label: 0
  no-extra-parens: 0
  no-extra-semi: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-func-assign: 2
  no-implicit-coercion: 0
  no-implicit-globals: 0
  no-implied-eval: 2
  no-inline-comments: 0
  no-inner-declarations: 2
  no-invalid-regexp: 2
  no-invalid-this: 2
  no-irregular-whitespace: 2
  no-iterator: 2
  no-label-var: 2
  no-labels: 2
  no-lone-blocks: 0
  no-lonely-if: 0
  no-loop-func: 0
  no-magic-numbers: 0
  no-mixed-requires: 2
  no-mixed-spaces-and-tabs: [2, false]
  no-multi-spaces: 2
  no-multi-str: 2
  no-multiple-empty-lines: 0
  no-native-reassign: 2
  no-negated-condition: 0
  no-negated-in-lhs: 2
  no-nested-ternary: 2
  no-new: 2
  no-new-func: 2
  no-new-object: 2
  no-new-require: 2
  no-new-symbol: 2
  no-new-wrappers: 2
  no-obj-calls: 2
  no-octal: 2
  no-octal-escape: 2
  no-param-reassign: 0
  no-path-concat: 2
  no-plusplus: 0
  no-process-env: 0
  no-process-exit: 2
  no-proto: 2
  no-redeclare: 2
  no-regex-spaces: 2
  no-restricted-globals: 0
  no-restricted-imports: 0
  no-restricted-modules: 0
  no-restricted-syntax: 0
  no-return-assign: 0
  no-script-url: 2
  no-self-assign: 2
  no-self-compare: 0
  no-sequences: 2
  no-shadow: 0
  no-shadow-restricted-names: 2
  no-spaced-func: 2
  no-sparse-arrays: 2
  no-sync: 0
  no-ternary: 0
  no-trailing-spaces: 2
  no-this-before-super: 2
  no-throw-literal: 0
  no-undef: 2
  no-undef-init: 2
  no-undefined: 0
  no-unexpected-multiline: 2
  no-underscore-dangle: [2, {allowAfterThis: true}]
  no-unmodified-loop-condition: 2
  no-unneeded-ternary: 0
  no-unreachable: 2
  no-unsafe-finally: 0
  no-unused-expressions: 2
  no-unused-labels: 2
  no-unused-vars: [2, {vars: "all", args: "after-used"}]
  no-use-before-define: 0
  no-useless-call: 0
  no-useless-computed-key: 0
  no-useless-concat: 2
  no-useless-constructor: 0
  no-useless-escape: 0
  no-void: 0
  no-var: 0
  no-warning-comments: 0
  no-whitespace-before-property: 2
  no-with: 2
  object-curly-spacing: [0, "never"]
  object-shorthand: 0
  one-var: 0
  one-var-declaration-per-line: 0
  operator-assignment: 0
  operator-linebreak: 0
  padded-blocks: 0
  prefer-arrow-callback: 0
  prefer-const: 0
  prefer-reflect: 0
  prefer-rest-params: 0
  prefer-spread: 0
  prefer-template: 0
  quote-props: 0
  quotes: [2, "single"]
  radix: 0
  require-jsdoc: 0
  require-yield: 0
  semi: 2
  semi-spacing: [2, {before: false, after: true}]
  sort-imports: 0
  sort-vars: 0
  space-before-blocks: 2
  space-before-function-paren: [2, "never"]
  space-in-parens: 0
  space-infix-ops: 2
  space-unary-ops: [2, {words: true, nonwords: false}]
  spaced-comment: [2, "always", {exceptions: ["-", "="]}]
  strict: 0
  template-curly-spacing: 0
  use-isnan: 2
  valid-jsdoc: [2, {prefer: {return: "returns"}}]
  valid-typeof: 2
  vars-on-top: 0
  wrap-iife: 2
  wrap-regex: 0
  yield-star-spacing: 0
  yoda: [2, "never"]
