/*tslint:disable:max-line-length*/

export class Section {
    constructor(
        public header: string,
        public content: string,
    ) {
    }
}

export const SECTION_1_CONTENT: string =
`<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac tempus nulla. Nam justo felis, sollicitudin a pretium in, pulvinar non tortor. Praesent consequat leo erat, vel blandit purus cursus non. Phasellus a dui ullamcorper, maximus sapien eget, faucibus arcu. Etiam vehicula varius ante, et finibus mauris rhoncus ac. Mauris ut massa porta arcu pretium sagittis. Phasellus convallis nibh magna, et venenatis lectus cursus sed. Fusce ac interdum elit. Sed aliquet, libero nec ornare accumsan, leo felis scelerisque lorem, at cursus sem magna elementum nunc. Nunc eu tempor mauris. Quisque id tellus lectus.</p>

<p>Nulla eget congue odio. Pellentesque ligula est, ullamcorper at purus sit amet, varius rutrum turpis. Nunc scelerisque tincidunt dolor id varius. In maximus blandit est aliquet accumsan. Nam non sollicitudin nibh. Nulla consectetur nisl nulla. Nam dignissim, nisl sit amet elementum porta, lectus ipsum imperdiet nulla, id congue ligula neque ut purus. Proin volutpat ultricies mi, sit amet pharetra mauris ornare in. Praesent tortor nulla, pretium vestibulum finibus quis, congue at libero. In laoreet, erat vel lacinia imperdiet, erat enim vestibulum erat, quis rhoncus neque enim quis enim. Curabitur congue, neque nec pulvinar lacinia, nisl enim suscipit ligula, ac interdum turpis metus ut ex. Aenean efficitur congue turpis eu lobortis.</p>

<p>Nam sollicitudin ac mi non varius. Maecenas tellus turpis, tempor a imperdiet et, scelerisque nec justo. Pellentesque lacinia ac massa varius ultricies. Maecenas in purus vel nulla sodales malesuada. Duis aliquam elit ut neque blandit lacinia et in nibh. Suspendisse vestibulum ligula lorem, ac consectetur justo molestie quis. Cras pellentesque elementum vehicula. Fusce tincidunt quam id erat convallis maximus. Praesent efficitur ornare nulla eu laoreet. Sed luctus eros ac sagittis dignissim. Cras tincidunt maximus nulla efficitur mattis. Praesent neque ex, faucibus et semper rhoncus, gravida ac felis. Fusce commodo iaculis mauris eu porttitor. Duis ut ultrices sem.</p>

<p>Ut volutpat magna aliquet efficitur finibus. Praesent vitae tempor ante, vitae vehicula dui. Donec tristique nunc et ornare porttitor. Nulla facilisi. Nunc maximus arcu mauris, vitae lacinia magna congue sed. Sed pulvinar eros turpis, vitae aliquam elit dignissim eget. Morbi elementum orci eget sem pellentesque mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse eget purus purus.</p>

<p>Donec nec nisl commodo, posuere quam eget, egestas dolor. Suspendisse consequat sapien neque, vel volutpat est porta nec. Sed pellentesque malesuada est non scelerisque. Nulla id dapibus nisl. Donec gravida enim vel magna cursus, quis mollis mauris maximus. Sed gravida nec arcu sit amet consectetur. Integer cursus metus nec dui ultricies, nec aliquam justo consectetur. Integer condimentum justo urna, nec accumsan ligula interdum eget. Nunc at tincidunt orci. Vestibulum mattis, erat ac pellentesque consequat, turpis est elementum mauris, in interdum nisl sem sit amet quam.</p>
`;

export const SECTION_2_CONTENT: string =
`<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce porttitor porttitor purus, in congue nisi vulputate ac. Curabitur vel nibh pellentesque mi dapibus pellentesque et vitae nunc. Phasellus vitae rhoncus lacus. Morbi laoreet malesuada turpis, non rhoncus tortor fringilla id. Etiam sed pharetra lorem. Praesent eu nibh a nisi ullamcorper mattis ac vitae lacus. Vivamus vel placerat eros.</p>

<p>Nam facilisis vestibulum sapien, ac consequat dolor porta sed. Integer nec pretium ligula. Vivamus bibendum nunc et enim condimentum tempor. Phasellus ut velit ultrices, lacinia risus nec, lobortis est. Nullam eget vehicula lorem. Vestibulum tristique bibendum ante ac pharetra. Cras in magna pharetra, lobortis neque vel, mollis felis.</p>`;

export const SECTION_3_CONTENT: string =
`<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fringilla elit quis tempus cursus. Maecenas sed arcu scelerisque, commodo elit in, euismod nibh. Nunc placerat, dolor vitae feugiat rutrum, ligula libero hendrerit ligula, at suscipit neque risus in est. Aliquam et erat at ex porttitor semper. Maecenas feugiat sem neque. Aenean ac urna a tellus facilisis molestie non eget quam. Nunc lacinia tincidunt augue eget maximus. Praesent nunc mauris, commodo eu accumsan vel, consectetur nec mauris. Morbi interdum, mi a tincidunt bibendum, velit odio efficitur magna, eu congue arcu tortor quis enim. Nulla pellentesque mi ac mattis sagittis. Cras tincidunt, est quis imperdiet feugiat, ex lacus convallis magna, a sollicitudin odio neque eu nulla. Ut sed nunc euismod, lacinia lectus a, efficitur ante.</p>

<p>Vivamus ex justo, sollicitudin ac scelerisque et, fermentum consectetur nunc. Suspendisse luctus, diam et aliquam sagittis, metus nisi dictum turpis, id convallis felis arcu at nisl. Suspendisse iaculis ligula ac pellentesque pretium. Etiam facilisis sed orci at rhoncus. Nullam tempus vestibulum nunc lacinia porttitor. Vivamus diam magna, elementum a nunc sed, tempor ultricies risus. Aliquam bibendum consectetur enim. Vestibulum interdum nisl lacus, a blandit magna porta quis. Donec gravida consequat lectus. Aenean et tristique nisl. Phasellus porta nulla dolor, nec ultricies erat pellentesque ac. Mauris vitae nunc ut massa tempus vulputate non nec eros. Donec sit amet euismod lacus, a vehicula justo. Donec commodo lorem ac tincidunt efficitur. Praesent scelerisque, lectus eu fermentum ornare, mauris mauris ornare mi, id tincidunt nulla nisi vitae erat.</p>

<p>Vestibulum elementum tincidunt neque. Pellentesque interdum enim ornare laoreet lobortis. Nunc mauris dolor, porta quis diam gravida, imperdiet tincidunt ante. Donec dictum ante arcu, ut interdum diam lobortis non. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam hendrerit luctus urna, quis eleifend purus pretium quis. Nam fermentum, dui eu consectetur ultrices, enim lacus tempus elit, vel malesuada elit purus id dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In pretium, mauris quis consequat convallis, dui arcu gravida dolor, a accumsan arcu turpis in nisi. Donec erat sapien, malesuada sed ligula sed, semper vehicula nisl. Sed id mauris augue.</p>

<p>Cras eros nulla, lobortis nec mollis quis, pretium eget quam. Donec augue tortor, iaculis nec posuere eu, pharetra at massa. Pellentesque vitae elit pellentesque, congue ligula eu, mattis lorem. Praesent eget risus nec diam blandit ornare vitae quis tellus. Aenean bibendum est in metus maximus, non finibus nulla sagittis. Vivamus velit urna, eleifend eu enim a, rhoncus aliquam nunc. Nullam ac erat ultrices, ultricies ipsum eu, gravida purus. In iaculis ornare enim, nec scelerisque diam lacinia at. Maecenas turpis urna, volutpat vitae interdum id, hendrerit scelerisque ipsum. Cras rutrum blandit mi, non pellentesque enim facilisis sit amet. Sed efficitur hendrerit magna, eu pharetra dolor tristique eget.</p>

<p>Nulla tincidunt, leo ultrices feugiat dapibus, odio metus aliquet sapien, vitae gravida risus nisl vitae sem. Morbi fermentum velit et odio pellentesque iaculis. Aliquam non odio purus. Nullam luctus, purus quis semper bibendum, dui nibh posuere velit, sit amet malesuada urna enim ac magna. Vestibulum commodo faucibus est, vitae mollis ipsum interdum vel. Curabitur semper accumsan dui, vel euismod metus porttitor non. Nunc vestibulum ac odio eget pulvinar. Proin auctor interdum posuere. Ut faucibus porttitor vestibulum. Nullam aliquam nec est in pretium.</p>

<p>Cras non venenatis nunc, vel mattis augue. Donec id tempus dolor, non tempor dui. Nullam ultricies aliquam massa a consectetur. Donec condimentum purus quis est varius vestibulum. Praesent malesuada ultrices ante. Morbi sagittis faucibus tortor, quis hendrerit lacus. Nam ut leo sit amet magna interdum aliquam. Morbi pretium, mauris et ultricies laoreet, mauris tortor convallis ipsum, id tincidunt metus quam et massa. Sed a imperdiet enim.</p>

<p>Ut dui turpis, varius eu viverra vitae, commodo vitae nulla. Duis vestibulum condimentum eros in facilisis. Nulla bibendum, lacus vitae molestie laoreet, libero nulla finibus nunc, lobortis iaculis enim purus sed sapien. Nulla quis erat tortor. Donec id commodo lectus. Praesent neque nulla, eleifend at dolor id, lobortis luctus nibh. Curabitur non mauris tempor, pharetra lorem id, auctor mauris. Phasellus lacinia sollicitudin congue. In imperdiet ante mauris, in vestibulum ligula fermentum ac. Proin id vehicula urna, eu maximus tellus. Quisque convallis arcu ante, in commodo ante vehicula quis. Vivamus blandit consequat est ut tristique. Fusce hendrerit pulvinar suscipit. Mauris erat neque, interdum sit amet magna id, imperdiet rutrum lectus.</p>`;

export const SECTIONS: Section[] = [
    new Section('Section 1', SECTION_1_CONTENT),
    new Section('Section 2', SECTION_2_CONTENT),
    new Section('Section 3', SECTION_3_CONTENT)];
